#!/bin/bash

CFGDIR="$HOME/.tvcfg"
CHANNEL=""
PROGRAM=""

if [ -z "$1" ]; then
    echo "Usage: $0 <channel_num | network_name | callsign>"
    exit 1
fi

# device id of homerun
DEVICE=`hdhomerun_config discover | awk '{print $3}'`

# could use a better channel mapping

shopt -s nocasematch
case "$1" in
    "help" | "list" )
	echo "Available channels"
	cat $CFGDIR/tuner*.cfg | awk -F":" '{print $3}' | column
	exit 0
	;;
    "stop" )
	echo "setting tuners to none"
	hdhomerun_config $DEVICE set /tuner0/channel none
	hdhomerun_config $DEVICE set /tuner1/channel none
	exit 0
	;;
    *)
	while IFS=':' read -r mychannel myprogram callsign
	  do
        	echo "trying Channel $mychannel Program $myprogram"
        	export CHANNEL="${mychannel}"
        	export PROGRAM="${myprogram}"
	done < <(cat $CFGDIR/tuner*.cfg | egrep -E "^.*:(${1} .*$)|^.*:.*:* (${1})$")
	TUNER=`grep -H -E "^.*:(${1} .*$)|^.*:.*:* ($1)$" $CFGDIR/tuner*.cfg | awk -F":" '{print $1}' | tr -d -c 0-9`
        ;;
esac
echo "-----------------------"
echo "tuner - . $TUNER ."
echo "channel - . "${CHANNEL}" ."
echo "program - . "${PROGRAM}" ."


# this computer's ip address I want the Homerun to connect to
MY_IP=`ifconfig eth0 | grep inet | grep -v inet6 | awk '{print $2}'`
#if [ -z "$MY_IP" ]; then
#    MY_IP=`ifconfig en1 | grep inet | grep -v inet6 | awk '{print $2}'`
#fi

# arbitrary port for VLC to listen on
RTP_PORT=5000

# tuner id
#TUNER=0

# won't work if VLC is already running
killall -9 vlc > /dev/null 2>&1
sleep 1

# start VLC listening for stream
##open /Applications/VLC.app --args rtp://@:$RTP_PORT
vlc --deinterlace -1 rtp://@:$RTP_PORT >/dev/null 2>&1 &
sleep 4

# set the tuner channel
echo "setting the tuner $CHANNEL"
hdhomerun_config $DEVICE set /tuner$TUNER/channel auto:$CHANNEL

# set the program id
echo "setting the program id $PROGRAM"
hdhomerun_config $DEVICE set /tuner$TUNER/program $PROGRAM

# tell it to send the video stream our way
hdhomerun_config $DEVICE set /tuner$TUNER/target rtp://$MY_IP:$RTP_PORT

while [ $(pidof vlc) ];
 do
	 MESSAGE=$(cat $CFGDIR/tuner*.cfg | egrep -E "^.*:(${1} .*$)|^.*:.*:* (${1})$" | awk -F":" '{print $3}')
	 echo "Watching $MESSAGE "
	 sleep 8
	 clear
done
sleep 1
echo "exiting , setting tuners to none"
hdhomerun_config $DEVICE set /tuner0/channel none
hdhomerun_config $DEVICE set /tuner1/channel none
